swagger:
  enable: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tw_wallet
    username: postgres
    password: tw-wallet-2020
    driver-class-name: org.postgresql.Driver
  jooq:
    database:
      name: org.jooq.meta.postgres.PostgresDatabase
      inputSchema: public

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5

  flyway:
    enabled: true
    locations: filesystem:src/main/resources/migration,classpath:migration

quorum:
  rpc:
    url: 'http://quorum.tw-wallet.in2e.com:22001'
  dc-ep:
    contract-address: '0x624d400315312c6280F6dB7683ACf2128EbB9d46'
    url: 'http://quorum.tw-wallet.in2e.com:22001'
  identity-registry:
    contract-address: '0xfb87495Ab114664d5bEb3Ce9Efb8fBc08fc18C36'
  health-verification-claim:
    contract-address: '0xc4F5D965d797e807F5014AC944E48D5ecCa29Eb9'
    issuer-did: '0xcA843569e3427144cEad5e4d5999a3D0cCF92B8e'
    issuer-address: '0x47187406E7dA648AcF3E6761eFC00660fcd7A0C6'
    issuer-private-key: '1cf09fe5283831f39add043b66ad202948ebb9bf994e2d09cf00dd2279b1d6b2'
  node1:
    private-key: '0x4762E04D10832808A0AEBDAA79C12DE54AFBE006BFFFD228B3ABCC494FE986F9'
#    address: '0x86e961c7b74f760fe5DF0623f1bBD048c643F653'
#    public-key: '0x036c45647d628602b863b7571a39d3f771cef5e8f9c5e8f954c6b5342e7394d908'

