swagger:
  enable: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tw_wallet
    username: postgres
    password: tw-wallet-2020
    driver-class-name: org.postgresql.Driver
  jooq:
    database:
      name: org.jooq.meta.postgres.PostgresDatabase
      inputSchema: public

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5

  flyway:
    enabled: true
    locations: filesystem:src/main/resources/migration,classpath:migration

quorum:
  rpc:
    url: 'http://quorum.tw-wallet.in2e.com:22001'
#    url: 'http://127.0.0.1:22001'
  tw-point:
    contract-address: '0x624d400315312c6280F6dB7683ACf2128EbB9d46'
  identity-registry:
    contract-address: '0x11aC39ac7D780a6b9DdfC8687831e25B655884c7'
  health-verification-claim:
    contract-address: '0x81845481fD51Efd88fd44e8983a60CEcF3886552'
    issuer-address: '0xcA843569e3427144cEad5e4d5999a3D0cCF92B8e'
    issuer-private-key: '4762e04d10832808a0aebdaa79c12de54afbe006bfffd228b3abcc494fe986f9'
  node1:
    private-key: '0x4e77046ba3f699e744acb4a89c36a3ea1158a1bd90a076d36675f4c883864377'
