server:
  port: 8080

swagger:
  enable: true

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jooq:
    database:
      name: org.jooq.meta.postgres.PostgresDatabase
      inputSchema: public


quorum:
  rpc:
    url: ${RPC_URL}
  dc-ep:
    contract-address: ${TWPOINT_CONTRACT_ADDRESS}
  identity-registry:
    contract-address: ${IDENTITY_REGISTRY_CONTRACT_ADDRESS}
  node1:
    private-key: ${NODE1_PRIVATE_KEY}