swagger:
  enable: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tw_wallet
    name: pg-sync
    username: postgres
    password: tw-wallet-2020
    driver-class-name: org.postgresql.Driver
  jooq:
    database:
      name: org.jooq.meta.postgres.PostgresDatabase
      inputSchema: public

quorum:
  rpc:
    urls:
      - ${RPC_URL1}
      - ${RPC_URL2}
      - ${RPC_URL3}
      - ${RPC_URL4}
  dc-ep:
    contract-address: '0x624d400315312c6280F6dB7683ACf2128EbB9d46'
  identity-registry:
    contract-address: '0x11aC39ac7D780a6b9DdfC8687831e25B655884c7'
  node1:
    private-key: '0x4e77046ba3f699e744acb4a89c36a3ea1158a1bd90a076d36675f4c883864377'
