server:
  port: 8080

spring:
  profiles:
    active: ${PROJECT_ENV:local}

  datasource:
    driver-class-name: org.postgresql.Driver
    name: service-contract
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

quorum:
  rpc:
    urls:
      - ${RPC_URL1}
      - ${RPC_URL2}
      - ${RPC_URL3}
      - ${RPC_URL4}
  dc-ep:
    contract-address: ${TWPOINT_CONTRACT_ADDRESS}
    contract-address-new: ${DCEP_CONTRACT_ADDRESS}
  identity-registry:
    contract-address: ${IDENTITY_REGISTRY_CONTRACT_ADDRESS}
  identities:
    contract-address: ${IDENTITIES_CONTRACT_ADDRESS}
  health-verification-claim:
    contract-address: ${HEALTH_VERIFICATION_CLAIM_CONTRACT_ADDRESS}
    issuer-address: ${HEALTH_VERIFICATION_CLAIM_ISSUER_ADDRESS}
    issuer-private-key: ${HEALTH_VERIFICATION_CLAIM_ISSUER_PRIVATE_KEY}
  node1:
    private-key: ${NODE1_PRIVATE_KEY}


sync:
  interval: 3000
  block-stop-increase: 10


