server:
  port: 8080

spring:
  profiles:
    active: ${PROJECT_ENV:local}

  datasource:
    driver-class-name: org.postgresql.Driver
    name: service-contract
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
    show-sql: false

  flyway:
    enabled: true

  rabbitmq:
    host: ${RABBIT_MQ_URL}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5