swagger:
  enable: true

spring:
  datasource:
    url: jdbc:h2:~/tw_wallet
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jooq:
    database:
      name: org.jooq.meta.h2.H2Database

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5

  flyway:
    enabled: false
    locations: filesystem:src/main/resources/h2/migration

quorum:
  rpc:
    url: 'http://quorum.tw-wallet.in2e.com:22001'
  tw-point:
    contract-address: '0x9d13C6D3aFE1721BEef56B55D303B09E021E27ab'
  identity-registry:
    contract-address: '0x11aC39ac7D780a6b9DdfC8687831e25B655884c7'
  node1:
    private-key: '0x4e77046ba3f699e744acb4a89c36a3ea1158a1bd90a076d36675f4c883864377'
