---
version: '2'
services:
  backend:
    image: ${TW_WALLET_IMAGE}
    user: root
    volumes:
      - ${LOG_DIR}/backend:/app/logs
    environment:
      PROJECT_ENV: dev
      DB_URL: ${HOST_IP}
      DB_PORT: 5432
      DB_NAME: tw_wallet
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RPC_URL: ${RPC_URL}
      TWPOINT_CONTRACT_ADDRESS: ${TWPOINT_CONTRACT_ADDRESS}
      IDENTITY_REGISTRY_CONTRACT_ADDRESS: ${IDENTITY_REGISTRY_CONTRACT_ADDRESS}
      HEALTH_VERIFICATION_CLAIM_CONTRACT_ADDRESS: ${HEALTH_VERIFICATION_CLAIM_CONTRACT_ADDRESS}
      HEALTH_VERIFICATION_CLAIM_ISSUER_ADDRESS: ${HEALTH_VERIFICATION_CLAIM_ISSUER_ADDRESS}
      HEALTH_VERIFICATION_CLAIM_ISSUER_PRIVATE_KEY: ${HEALTH_VERIFICATION_CLAIM_ISSUER_PRIVATE_KEY}
      NODE1_PRIVATE_KEY: ${NODE1_PRIVATE_KEY}
      LOG_DIR: ${LOG_DIR}
      swagger.enable: 'true'
      server.port: 8080
    ports:
      - "80:8080"
    networks:
      - backend

  sync:
    image: ${TW_WALLET_IMAGE}
    user: root
    volumes:
      - ${LOG_DIR}/sync:/app/logs
    command: ["java", "-jar", "tw-wallet-sync.jar"]
    environment:
      PROJECT_ENV: dev
      DB_URL: ${HOST_IP}
      DB_PORT: 5432
      DB_NAME: tw_wallet
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RPC_URL: ${RPC_URL}
      TWPOINT_CONTRACT_ADDRESS: ${TWPOINT_CONTRACT_ADDRESS}
      IDENTITY_REGISTRY_CONTRACT_ADDRESS: ${IDENTITY_REGISTRY_CONTRACT_ADDRESS}
      NODE1_PRIVATE_KEY: ${NODE1_PRIVATE_KEY}
      LOG_DIR: ${LOG_DIR}
      swagger.enable: 'true'
      server.port: 8080
    depends_on:
      - backend
    networks:
      - backend

networks:
  backend:
    driver: bridge
