---
version: '2'
services:
  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tw-wallet-2020
      - POSTGRES_DB=tw_wallet
    ports:
      - "5432:5432"